log:
  level: -1
  enableJson: false
database:
  connectionStringPostgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: postgres
    sslMode: disable
observability:
  serviceName:
  endpoint:
  enabled: