log:
  level: -1
  enableJson: false
database:
  connectionStringPostgres:
    #uri: postgres://fxurerfl:R71RUnRpWkRRvpm3gbhUJ3pmlq2FVKoP@flora.db.elephantsql.com/fxurerfl
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: postgres
    sslMode: disable
observability:
  serviceName:
  endpoint:
  enabled: