log:
  level: -1
  enableJson: false
database:
  connectionStringPostgres:
    # TODO: changes settings
    #uri: postgres://fxurerfl:R71RUnRpWkRRvpm3gbhUJ3pmlq2FVKoP@flora.db.elephantsql.com/fxurerfl
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: postgres
    sslMode: disable
observability:
  serviceName:
  endpoint: "192.168.3.6:4317" # NOTE - changes IP address
  enabled: