log:
  level: -1
  enableJson: false

database:
  connectionStringPostgres:
    #uri: postgres://fxurerfl:R71RUnRpWkRRvpm3gbhUJ3pmlq2FVKoP@flora.db.elephantsql.com/fxurerfl
    host: flora.db.elephantsql.com
    port: 5432
    user: fxurerfl
    password: R71RUnRpWkRRvpm3gbhUJ3pmlq2FVKoP
    dbname: fxurerfl
    sslMode: disable

observability:
<<<<<<< HEAD
  serviceName: "pippo-service"
  endpoint: "192.168.3.2:4317" # TODO: check if ip address is correct
=======
  serviceName: "book-store-be"
  endpoint: "192.168.3.6:4317" # TODO: check if ip address is correct
>>>>>>> 6cdf36f129ffb0ecedf862d02e0d56d08b5e2efd
  enabled: