log:
  level: -1
  enableJson: false
database:
  connectionStringPostgres:
    #uri: postgres://fxurerfl:R71RUnRpWkRRvpm3gbhUJ3pmlq2FVKoP@flora.db.elephantsql.com/fxurerfl
    host: flora.db.elephantsql.com
    port: 5432
    user: fxurerfl
    password: R71RUnRpWkRRvpm3gbhUJ3pmlq2FVKoP
    dbname: fxurerfl
    sslMode: disable
observability:
  serviceName:
  endpoint: "192.168.3.7:4317" # NOTE - changes IP address
  enabled: