version: "3.8"

services:
  # Jaeger All In One
  jaeger-all-in-one:
    image: 'jaegertracing/all-in-one:1'
    restart: always
    ports:
      - '16686:16686'
      - '14268'
      - '14250'

  # Otel Collector
  otel-collector:
    image: 'otel/opentelemetry-collector-contrib:0.68.0'
    restart: always
    command:
      - '--config=/etc/otel-collector-config.yaml'
    volumes:
      - './configuration/otel-collector-config.yaml:/etc/otel-collector-config.yaml'
    ports:
      - '1888:1888'   # pprof extension
      - '8888:8888'   # Prometheus metrics exposed by the collector
      - '8889:8889'   # Prometheus exporter metrics
      - '13133:13133' # health_check extension
      - '4317:4317'   # OTLP gRPC receivers
    depends_on:
      - jaeger-all-in-one
      - prometheus

  # Prometheus
  prometheus:
    image: 'prom/prometheus:v2.47.1'
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - './configuration/prometheus.yaml:/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'

  # Grafana
  grafana:
    image: 'grafana/grafana:9.0.1'
    restart: always
    volumes:
      - ./configuration/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./configuration/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - '3000:3000'