version: "3.8"

services:
  jaeger-all-in-one:
    image: 'jaegertracing/all-in-one:1'
    restart: always
    ports:
      - '16686:16686'
      - '14268'
      - '14250'
  otel-collector:
    image: 'otel/opentelemetry-collector-contrib:0.68.0'
    restart: always
    command:
      - '--config=/etc/otel-collector-config.yaml'
    volumes:
      - './otel-collector-config.yaml:/etc/otel-collector-config.yaml'
    ports:
      - '1888:1888'
      - '8888:8888'
      - '8889:8889'
      - '13133:13133'
      - '4317:4317'
    depends_on:
      - jaeger-all-in-one