receivers:
  otlp:
    protocols:
      grpc:
  prometheus:

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
  
  prometheus:
    endpoint: 0.0.0.0:8889

  logging:

processors:
  batch:

extensions:
    health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]