receivers:
  otlp:
    protocols:
      grpc:

exporters:
  jaeger:
      endpoint: jaeger-all-in-one:14250
      tls:
        insecure: true

  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

processors:
  batch:

extensions:
    health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]