basePath: /api/v1
definitions:
  models.Book:
    properties:
      autore:
        example: Ruben Fabrizi
        maxLength: 64
        type: string
      categoria:
        example: New Releases
        type: string
      copertina:
        example: Hard Cover
        type: string
      genere:
        example: Romance
        type: string
      id:
        type: integer
      id_copertina:
        example: 564
        type: integer
      prezzo:
        example: 15.9
        type: number
      quantita:
        example: 2
        maximum: 5
        minimum: 1
        type: integer
      summary:
        example: Lorem Ipsum is simply dummy text of the printing and typesetting
          industry.
        maxLength: 512
        type: string
      titolo:
        example: Il silenzio di un mare in tempesta
        maxLength: 255
        type: string
    required:
    - autore
    - categoria
    - copertina
    - genere
    - id_copertina
    - prezzo
    - quantita
    - summary
    - titolo
    type: object
  responses.Response:
    properties:
      message:
        type: string
    type: object
host: 192.168.3.6:8000
info:
  contact:
    email: chrisd3v3l0p3r@gmail.com
    name: Chris Developer
  description: API for manages a book store
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Book Store API
  version: "1.0"
paths:
  /book:
    get:
      description: Get details for every book
      parameters:
      - description: Number of the pagination
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Book'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Response'
      summary: Get books
      tags:
      - Book
  /book/:
    post:
      consumes:
      - application/json
      description: Adds new book
      parameters:
      - description: Adds new book
        in: body
        name: models.Book
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Response'
      summary: Adds a book
      tags:
      - Book
  /book/{id}:
    delete:
      description: Delete a book with same ID
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Response'
      summary: Delete a book
      tags:
      - Book
    get:
      consumes:
      - application/json
      description: Get details of a book
      parameters:
      - description: Title of the book
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Response'
      summary: Get a book
      tags:
      - Book
    put:
      description: |-
        Update all details of a book
        The title cannot be more than 255 characters.
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      - description: Book
        in: body
        name: title
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Response'
      summary: Updates the book
      tags:
      - Book
swagger: "2.0"
